# Generated by Django 2.2 on 2021-09-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210902_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentor',
            new_name='User',
        ),
    ]
