# Generated by Django 2.2 on 2021-09-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_auto_20210902_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='user',
        ),
    ]
