# Generated by Django 2.2 on 2021-09-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20210902_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
